rss/urls.py
from django.urls import path
from rss.views import RssFeedUserCreateView, RssFeedUserListView, FeddEntriesList, RssFeedUserUpdateView, \
    CancelSubscriptionRedirect

urlpatterns = [
    path('subscribe/', RssFeedUserCreateView.as_view(), name="create-rss"),
    path('subscribe/<str:pk>/', RssFeedUserUpdateView.as_view(), name="update-rss"),
    path('cancel-subscribe/<str:pk>/', CancelSubscriptionRedirect.as_view(), name="cancel-rss"),
    path('subscriptions/', RssFeedUserListView.as_view(), name="rss-list"),
    path('entries/<str:pk>/', FeddEntriesList.as_view(), name="feed-entries"),

]

rss_reader/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include(('users.urls', 'users'), namespace='users')),
                  path('rss/', include(('rss.urls', 'rss'), namespace='rss')),
              ] + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from users.views import UserCreateView

urlpatterns = [
    path('sign-up/', UserCreateView.as_view(), name="create-user"),
    path('', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

rss/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class RssFeedUser(models.Model):
    """
    Model for user and RSS Feed
    """
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    title = models.CharField(max_length=100)
    feed_url = models.CharField(max_length=100)
    creation_date = models.DateTimeField(default=timezone.now)
    description = models.CharField(max_length=200)
    subscribed = models.BooleanField(default=True)
    last_update = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.title


class FeedEntries(models.Model):
    """
    Model for entries
    """
    feed = models.ForeignKey(RssFeedUser, on_delete=models.PROTECT)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    link = models.CharField(max_length=2048)
    published = models.DateTimeField(blank=True, null=True)
    external_id = models.CharField(max_length=2048, unique=True)

    def __str__(self):
        return self.feed.title

users/models.py
from django.db import models

# Create your models here.

rss/forms.py
from django import forms
from django.forms import ModelForm

from rss.models import RssFeedUser


class RssFeedUserForm(ModelForm):
    description = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = RssFeedUser
        exclude = ['user', 'subscribed', ]
        fields = ['title', 'feed_url', 'description', ]

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=30, required=False)
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'password1', 'password2',)

rss/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, ListView, TemplateView, UpdateView, RedirectView
from django.urls import reverse_lazy
from rss.forms import RssFeedUserForm
from rss.models import RssFeedUser, FeedEntries
from rss.tasks import save_new_rss_subscription_task


class RssFeedUserCreateView(LoginRequiredMixin, CreateView):
    """
    View for creation User and RSS Feed relation
    """
    model = RssFeedUser
    form_class = RssFeedUserForm
    template_name = 'rss/rss_subscription.html'
    success_url = reverse_lazy('rss:rss-list')

    def form_valid(self, form):
        rss = form.save(commit=False)
        rss.user = self.request.user
        form.save()
        save_new_rss_subscription_task.delay(form.instance.pk)
        return super(RssFeedUserCreateView, self).form_valid(form)


class RssFeedUserUpdateView(LoginRequiredMixin, UpdateView):
    model = RssFeedUser
    form_class = RssFeedUserForm
    template_name = 'rss/rss_subscription.html'

    def get_success_url(self):
        feed_pk = self.kwargs['pk']
        return reverse_lazy('rss:feed-entries', kwargs={'pk': feed_pk})


class RssFeedUserListView(LoginRequiredMixin, ListView):
    """
    View for list user subcription
    """
    model = RssFeedUser

    def get_queryset(self):
        return RssFeedUser.objects.filter(user=self.request.user, subscribed=True)

    def get_context_data(self, **kwargs):
        context = super(RssFeedUserListView, self).get_context_data(**kwargs)
        context['unsubscribe'] = RssFeedUser.objects.filter(user=self.request.user, subscribed=False)
        return context


class FeddEntriesList(LoginRequiredMixin, TemplateView):
    """
    List for entries in a Feed
    """
    template_name = 'rss/feed_entries.html'

    def get_context_data(self, **kwargs):
        context = super(FeddEntriesList, self).get_context_data(**kwargs)
        user = self.request.user
        rss_feed = RssFeedUser.objects.get(id=self.kwargs['pk'])
        entries = FeedEntries.objects.filter(feed=rss_feed.id)
        context['user'] = user
        context['rss_feed'] = rss_feed
        context['entries'] = entries
        return context


class CancelSubscriptionRedirect(LoginRequiredMixin, RedirectView):
    """
    Cancel or Active RSS Subscription
    """
    is_permanent = True
    url = reverse_lazy('rss:rss-list')

    def dispatch(self, request, *args, **kwargs):
        self.cancel_rss_subscription()
        return super(CancelSubscriptionRedirect, self).dispatch(request, *args, **kwargs)

    def cancel_rss_subscription(self):
        rss = RssFeedUser.objects.get(id=self.kwargs["pk"])
        rss.subscribed = False if rss.subscribed else True
        rss.save()

users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth.models import User

from users.forms import SignUpForm


class UserCreateView(CreateView):
    model = User
    form_class = SignUpForm
    template_name = 'registration/signup_user.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.username = user.email
        form.save()
        return super(UserCreateView, self).form_valid(form)

templates/base.html
{% load static %}
<!DOCTYPE html>

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Django RSS Reader</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %} " rel="stylesheet">
    <link href="{% static 'css/form-validation.css' %}" rel="stylesheet">
    <link href="{% static 'css/sticky-footer-navbar.css' %}" rel="stylesheet">
    <link href="{% static 'fontawesome-free/css/all.css' %}" rel="stylesheet">
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>

</head>

<body class="bg-light">
{% include "navbar.html" %}
<main class="flex-shrink-0">
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</main>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
        crossorigin="anonymous"></script>
</body>

</html>

templates/navbar.html
<header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">RSS Reader</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="navbar-brand mr-1" href="{% url 'rss:rss-list' %}">RSS List</a>
                        </li>
{#                        <li class="nav-item">#}
{#                            <a class="navbar-brand mr-1" href="{% url 'rss:create-rss' %}">RSS Subscribe#}
{#                            <i class="fas fa-rss"></i></a>#}
{#                        </li>#}
                    {% endif %}
                </ul>
                {% if user.is_authenticated %}
                    <a class="navbar-brand mr-1" href="{% url 'users:logout' %}">logout
                        <i class="fas fa-sign-out-alt"></i></a>
                {% else %}
                    <a class="navbar-brand mr-1" href="{% url 'users:login' %}">LogIn
                        <i class="fas fa-sign-in-alt"></i></a>
                {% endif %}

            </div>
        </div>
    </nav>
</header>

templates/rss/feed_entries.html
{% extends 'base.html' %}

{% block content %}
    {% if rss_feed %}
        <h2>{{ rss_feed.title }}
            <a href="{% url 'rss:update-rss' rss_feed.pk %}">
                <i class="far fa-edit"></i>
            </a></h2>
        <h2>{{ rss_feed.last_update }}</h2>
        <br>
        {% if entries %}
            {% for entry in entries %}
                <div class="card">
                    <div class="card-body">
                        <h5 class=“card-title”>Headline: {{ entry.title }}</h5>
                        <p class=“card-text”>Description: {{ entry.description }}</p>
                        <a href="{{ entry.link }}" target="_blank" class="card-link">Visit Link</a>
                    </div>
                    <div class="card-footer">
                        <p>{% if entry.published %}{{ entry.published }} {% endif %}
                        </p>
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    {% endif %}
{% endblock %}

templates/rss/rss_subscription.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
    <h2>RSS Subscription</h2>
    <div class="col-md-7 col-lg-8">
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <br>
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
{% endblock %}

templates/rss/rssfeeduser_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-sm-10">
            <h2>RSS subscriptions</h2>
        </div>
        <div class="col-sm-2">
            <a class="btn btn-outline-dark btn-sm" href="{% url 'rss:create-rss' %}">RSS Subscribe
                <i class="fas fa-rss"></i></a>
        </div>
    </div>
    <div class="row">
        <ul class="list-group list-group-flush">
            {% for item in object_list %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <a href="{% url 'rss:feed-entries' item.pk %}"> {{ item }}</a>
                    <a href="{% url 'rss:cancel-rss' item.pk %}" data-bs-placement="top" title="Cancel">
                        <span class="badge bg-danger text-dark"><i class="fas fa-ban"></i></span></a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div class="row">
        {% if unsubscribe %}
            <div class="accordion accordion-flush" id="accordionFlushExample">
                <div class="accordion-item">
                    <h2 class="accordion-header" id="flush-headingOne">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                data-bs-target="#flush-collapseOne" aria-expanded="false"
                                aria-controls="flush-collapseOne">
                            Subscriptions Canceled
                        </button>
                    </h2>
                    <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne"
                         data-bs-parent="#accordionFlushExample">
                        <div class="accordion-body">
                            <ul class="list-group list-group-flush">
                                {% for item in unsubscribe %}
                                    <li class="list-group-item d-flex justify-content-between align-items-center">
                                        <a href="{% url 'rss:feed-entries' item.pk %}"> {{ item }}</a>
                                        <a href="{% url 'rss:cancel-rss' item.pk %}" data-bs-placement="top"
                                           title="Activate">
                                            <span class="badge bg-success text-dark"><i class="fas fa-check"></i></span></a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}